### ISSUE TITLE
Removing a vote or clearing votes not possible if multiple votes disabled for user

### ISSUE THREAD

**Issue by Hibbelharry** [ande3577/redmine_vote#20]
As it seems users are not able to remove a vote after they voted for an issue and if they're only permitted to supply a single vote, the buttons are missing. It's also not possible for a user to clear the votes after committing his single vote for an issue, even if he is permitted to do this. This was tested on Redmine 2.3.2 with redmine_vote checked out from git master on 23.07.2013 (5f434d35e7e4ac28a8a817bb6247cfed52185cd3)

**Comment by ande3577** [comment]
This is currently by design,  though I agree it is not the best implementation.  I will  look into chaning it so that the single vote permission is tied to a user's net vote count,  so if they up vote,  they will be able to downvote,  but not upvote again.  If they downvote to cancel their vote,  they will be able to up or down vote again.

**Comment by Hibbelharry** [comment]
Thx for your fast reply. Your proposed changes sound well fitting to our problems. Thx for your work, it is appreciated !

**Comment by ande3577** [comment]
Fixed in d203da34a9c2d0f731ab329b12451036cde827e2

Note that a user repeatedly up/down-voting will still affect vote totals/percentages, just not the vote count.

**Comment by Hibbelharry** [comment]
Thanks for your work ! Actually this fix improved situation a lot for us. Since the percentages are still wrong i'll open up another issue on that matter as a reminder. I think we don't need percentages to be 100% correct, but others might do and a user who is repeatedly voting up an down again is able to really abuse percentage statistics.
